image: node:8.16.2

pipelines:
  branches:
    master:
      - step:
          name: Install, build and tests
          image: jguyomard/laravel-php:7.1
          services:
            - docker
          caches:
            - docker
            - node
            - npm
            - composer
          script:
            - apk update
            - apk add zip
            - composer global require hirak/prestissimo
            - cp .env.prod .env
            - echo COMMIT=$BITBUCKET_COMMIT >> .env
            - composer install --optimize-autoloader --no-interaction --prefer-dist --ignore-platform-reqs
            - ls -la
            - cat .env
          artifacts:
            - vendor/**
            - .env
      - step:
          name: Deploy
          script:
            - apk update
            - apk add openssh
            - >-
              ssh -o ConnectTimeout=10 $SSH_USER_PRODUCTION@$SSH_HOST_PRODUCTION -p$SSH_PORT_PRODUCTION
              'cd /var/www/api-fornecedor.elomilhas.com.br;
               git pull origin master'
      - step:
          name: Clear Cache
          script:
            # Clear Cache
            - ssh -o ConnectTimeout=10 $SSH_USER_PRODUCTION@$SSH_HOST_PRODUCTION -p$SSH_PORT_PRODUCTION 'cd /var/www/api-fornecedor.elomilhas.com.br; composer dump; php artisan route:clear; php artisan config:clear'
      - step:
          name: Migrations & Seeds
          script:
            # Migrations
            - ssh -o ConnectTimeout=10 $SSH_USER_PRODUCTION@$SSH_HOST_PRODUCTION -p$SSH_PORT_PRODUCTION 'cd /var/www/api-fornecedor.elomilhas.com.br; php artisan migrate --force'
definitions:
  caches:
    npm: $HOME/.npm
