image: node:8.16.2

pipelines:
  branches:
    master:
      - step:
          name: Install, build and tests
          image: jguyomard/laravel-php:7.1
          services:
            - docker
          caches:
            - docker
            - node
            - npm
            - composer
          script:
            - apk update
            - apk add zip
            - composer global require hirak/prestissimo
            - cp .env.prod .env
            - echo COMMIT=$BITBUCKET_COMMIT >> .env
            - composer install --optimize-autoloader --no-interaction
            - ls -la
            - cat .env
          artifacts:
            - vendor/**
            - .env
      - step:
          name: Deploy to EC2
          services:
            - docker
          caches:
            - docker
          deployment: production
          script:
            - cat .env
            - cp .env prod.env
            - pipe: atlassian/rsync-deploy:0.3.2
              variables:
                USER: $SSH_USER_PRODUCTION
                SERVER: $SSH_HOST_PRODUCTION
                REMOTE_PATH: '/usr/share/nginx/api-fornecedor.elomilhas.com.br/'
                LOCAL_PATH: '*'
                EXTRA_ARGS: '--chown=www-data:www-data --chmod=ug=rwx,o=r --exclude=.git/** --exclude=node_modules/**'
      - step:
          name: Clear Cache
          script:
            - ssh -o ConnectTimeout=10 $SSH_USER_PRODUCTION@$SSH_HOST_PRODUCTION 'cd /usr/share/nginx/api-fornecedor.elomilhas.com.br; chown www-data:www-data -R vendor; chmod ug=rwx,o=r -R vendor; echo "permissions changed"'
            - ssh -o ConnectTimeout=10 $SSH_USER_PRODUCTION@$SSH_HOST_PRODUCTION 'cd /usr/share/nginx/api-fornecedor.elomilhas.com.br; composer dump; php artisan route:clear; php artisan config:clear'
definitions:
  caches:
    npm: $HOME/.npm
